### ISSUE TITLE
Failure when attached workbooks are unavailable

### ISSUE THREAD

**Issue by jeremyrsellars** [softek/CMS.HCPCS#2]
We encountered an issue when the Schedule B workbook referenced another workbook (which was not available).
```
Exception in thread "main" java.lang.RuntimeException: Could not resolve external workbook name 'file://///Co-adshare/share/Share/OA/CHPP/HAPGFrontOffice/DOCP2/Documentation/2021/2021%20Final%20Rule/Quarterly%20Updates/January%202021/2021%20Preliminary%20January%20IOCE%20Addendum%20B.10.29.20.xlsx'. Workbook environment has not been set up.
        at org.apache.poi.ss.formula.OperationEvaluationContext.createExternSheetRefEvaluator(OperationEvaluationContext.java:120)
        at org.apache.poi.ss.formula.OperationEvaluationContext.createExternSheetRefEvaluator(OperationEvaluationContext.java:91)
        at org.apache.poi.ss.formula.OperationEvaluationContext.getArea3DEval(OperationEvaluationContext.java:336)
        at org.apache.poi.ss.formula.WorkbookEvaluator.getEvalForPtg(WorkbookEvaluator.java:659)
        at org.apache.poi.ss.formula.WorkbookEvaluator.evaluateFormula(WorkbookEvaluator.java:516)
        at org.apache.poi.ss.formula.WorkbookEvaluator.evaluateAny(WorkbookEvaluator.java:278)
        at org.apache.poi.ss.formula.WorkbookEvaluator.evaluate(WorkbookEvaluator.java:220)
        at org.apache.poi.xssf.usermodel.BaseXSSFFormulaEvaluator.evaluateFormulaCellValue(BaseXSSFFormulaEvaluator.java:64)
        at org.apache.poi.ss.formula.BaseFormulaEvaluator.evaluate(BaseFormulaEvaluator.java:101)
        at dk.ative.docjure.spreadsheet$fn__403.invokeStatic(spreadsheet.clj:46)
        at dk.ative.docjure.spreadsheet$fn__403.invoke(spreadsheet.clj:43)
        at clojure.lang.MultiFn.invoke(MultiFn.java:229)
        at com.softekpanther.cms.hcpcs$sheet__GT_ScheduleBEntry_seq$fn__855$fn__856.invoke(hcpcs.clj:53)
        at clojure.core$map$fn__5866.invoke(core.clj:2753)
        at clojure.lang.LazySeq.sval(LazySeq.java:42)
        at clojure.lang.LazySeq.seq(LazySeq.java:51)
        at clojure.lang.RT.seq(RT.java:535)
        at clojure.lang.RT.countFrom(RT.java:650)
        at clojure.lang.RT.count(RT.java:643)
        at com.softekpanther.cms.hcpcs$sheet__GT_ScheduleBEntry_seq$fn__851.invoke(hcpcs.clj:61)
        at clojure.core$filter$fn__5893.invoke(core.clj:2817)
        at clojure.lang.LazySeq.sval(LazySeq.java:42)
        at clojure.lang.LazySeq.seq(LazySeq.java:51)
        at clojure.lang.RT.seq(RT.java:535)
        at clojure.core$seq__5402.invokeStatic(core.clj:137)
        at clojure.core$map$fn__5866.invoke(core.clj:2746)
        at clojure.lang.LazySeq.sval(LazySeq.java:42)
        at clojure.lang.LazySeq.seq(LazySeq.java:51)
        at clojure.lang.RT.seq(RT.java:535)
        at clojure.core$seq__5402.invokeStatic(core.clj:137)
        at clojure.core$map$fn__5866.invoke(core.clj:2746)
        at clojure.lang.LazySeq.sval(LazySeq.java:42)
        at clojure.lang.LazySeq.seq(LazySeq.java:51)
        at clojure.lang.ChunkedCons.chunkedNext(ChunkedCons.java:59)
        at clojure.lang.ChunkedCons.next(ChunkedCons.java:43)
        at clojure.lang.RT.next(RT.java:713)
        at clojure.core$next__5386.invokeStatic(core.clj:64)
        at clojure.core$zipmap.invokeStatic(core.clj:3079)
        at clojure.core$zipmap.invoke(core.clj:3071)
        at com.softekpanther.cms.hcpcs$_main$fn__927.invoke(hcpcs.clj:236)
        at clojure.core$map$fn__5866.invoke(core.clj:2755)
        at clojure.lang.LazySeq.sval(LazySeq.java:42)
        at clojure.lang.LazySeq.seq(LazySeq.java:51)
        at clojure.lang.Cons.next(Cons.java:39)
        at clojure.lang.RT.next(RT.java:713)
        at clojure.core$next__5386.invokeStatic(core.clj:64)
        at clojure.core$reduce1.invokeStatic(core.clj:944)
        at clojure.core$reduce1.invokeStatic(core.clj:934)
        at clojure.core$merge.invokeStatic(core.clj:3048)
        at clojure.core$merge.doInvoke(core.clj:3041)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.core$apply.invokeStatic(core.clj:667)
        at clojure.core$apply.invoke(core.clj:660)
        at com.softekpanther.cms.hcpcs$_main.invokeStatic(hcpcs.clj:237)
        at com.softekpanther.cms.hcpcs$_main.doInvoke(hcpcs.clj:227)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at com.softekpanther.cms.hcpcs.main(Unknown Source)
Caused by: org.apache.poi.ss.formula.CollaboratingWorkbooksEnvironment$WorkbookNotFoundException: Could not resolve external workbook name 'file://///Co-adshare/share/Share/OA/CHPP/HAPGFrontOffice/DOCP2/Documentation/2021/2021%20Final%20Rule/Quarterly%20Updates/January%202021/2021%20Preliminary%20January%20IOCE%20Addendum%20B.10.29.20.xlsx'. Workbook environment has not been set up.
        at org.apache.poi.ss.formula.CollaboratingWorkbooksEnvironment.getWorkbookEvaluator(CollaboratingWorkbooksEnvironment.java:194)
        at org.apache.poi.ss.formula.WorkbookEvaluator.getOtherWorkbookEvaluator(WorkbookEvaluator.java:170)
        at org.apache.poi.ss.formula.OperationEvaluationContext.createExternSheetRefEvaluator(OperationEvaluationContext.java:118)
        ... 56 more
```

**Comment by sir-wilhelm** [comment]
https://youtrack.softekinc.com/issue/panther-14557#focus=Comments-62-132546.0-0

I ran into this issue again, but it's easy to "break link" in excel to get it working.
